spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: SHENLAN@2016
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: false

server:
#  port: 8001
  port: 8002

logging:
  level:
    root: info

